import { Inter } from "next/font/google";
import Parallax_Provider from "@/components/Parallax_Provider";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CSIS 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/logo.jpeg" />
      <body className={inter.className}>
        <Parallax_Provider>
          {children}
        </Parallax_Provider>
      </body>
    </html>
  );
}
